{% set name = "pymapd" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 122ae15e3424d21a04ad771f6b097f7e30a847b377cf309f52e3b96fe698990b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - numpy 1.14.*
    - pyarrow >=0.10
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - pyarrow >=0.10,<0.13
    - pandas
    - six
    - sqlalchemy
    - thrift 0.11.*

test:
  imports:
    - pymapd
    - mapd

about:
  home: http://github.com/omnisci/pymapd
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'A python DB API 2 compatible client for mapd.'
  description: |
    A python DB API 2 compatible client for mapd.
  doc_url: https://pymapd.readthedocs.io
  dev_url: https://github.com/omnisci/pymapd

extra:
  recipe-maintainers:
    - TomAugspurger
    - andrewseidl
    - randyzwitch
    - xhochy
