travis:
  secure:
    BINSTAR_TOKEN: IILQRs7UOXs9/m2W9h5InzYkpf1wrmPi6EloacqoCwJBEbv9VokYLhQpnfI8/neL6pRAwk/Vff3WUirkFimD2qL/+qHAqF2O5uW2Neur70Tq/kW9FTDre82GBUz0K71iRlGqeCOdRsOoR6xx1G2FcbRV+sEJTAQM+G23DgDskK3zJhnpnyQlqANj1FSgD4Lfc03v6DhSkCy9YkgpNI41hZs07bkVlHXVJs7+V197dCVv/aSOAL2048m2KzXDcOcpd+K6Oy//EJvZfBPmkPWowDYtM4Hqkz/t3GWHsWRvTAHN44hmk31XUmp/AWuvkpg5TqUVERL2Dc/GAtlMQfaBAPWrCATCs4skES1xEdoQ21sImSgQvBDGzC0xrPCQhd45+0y4T4AYu0PSKBHQgemK49b9Ill85Jd//Y6gbz/2n7yu+dUUyD+eNkESnLhh9/yM+Ksj5EZnATFLeZ1n2k0PwWvRwdZEH7y2t+b+syZ7+l2eumrIp+MXZZZwrjCYL2jPt1wL73ViDTJIHAsMtoXx6huVsu0iJqGP1+BJO/Q9elyN/joq1eksv8604y8MgKVz5ftlAL6tvL4LEupxlBRAeWOotoOevym00BFZkcWI9ThcvliXPMMTyOIzCJdnh/A6R2gsJfHhlN6BhmjNQFNweAS/0rLDrs3yXWuSrGwf5f4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
